[workspace]
members = [
  "crates/aimd-core",
  "crates/aimd-cli",
]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/peakematt/aimd"
readme = "README.md"
authors = ["Matt Peake"]

[workspace.dependencies]
aimd-core = { path = "crates/aimd-core", version = "0.1.0" }
clap = { version = "4.5.53", features = ["derive", "wrap_help"] }
clap_complete = "4.5.61"
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
similar = "2.7.0"
tempfile = "3.23.0"
thiserror = "2.0.17"
